language: node_js

node_js:
  - "stable"

script:
  - "npm install"
  - "npm run build"
  - "npm test"

cache:
  directories:
    - "node_modules"

<<<<<<< HEAD
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
=======
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
>>>>>>> ch-setup-travis-#165316007

after_success:
  - npm run coverage
  - npm run report-coverage

after_success:
  - npm run coverage
  - npm run coveralls


