language: node_js

node_js:
  - "stable"

script:
  - "npm install"
  - "npm run build"
  - "npm test"

cache:
  directories:
    - "node_modules"

after_success:
  - npm run coverage
  - npm run report-coverage

after_success:
  - npm run coverage
  - npm run coveralls


